- name: Get list of FortiFlex Configurations for a Program
  hosts: localhost
  collections:
    - fortinet.fortiflexvm
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Get configs list
      fortinet.fortiflexvm.fortiflexvm_configs_list_info:
        username: "{{ username }}"
        password: "{{ password }}"
        # accountId: 12345 # optional
        programSerialNumber: "ELAVMS000000XXXX"
      register: result

    - name: Display response
      debug:
        var: result.configs