- name: Update entitlement
  hosts: localhost
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Update an entitlement.
      fortinet.fortiflexvm.fortiflexvm_entitlements_update:
        username: "{{ username }}"
        password: "{{ password }}"
        serialNumber: "FGVMXXXX00000000"
        # Please specify configId if you want to update configId, description or endDate
        configId: 12345
        # description: "Modify through Ansible" # Optional.
        # endDate: "2024-12-12T00:00:00"        # Optional. If not set, it will use the program end date automatically.
        # status: "ACTIVE"                      # Optional. ACTIVE or STOPPED
      register: result

    - name: Display response
      ansible.builtin.debug:
        var: result.entitlements
