- name: Get list of entitlements for a specific config ID
  hosts: localhost
  collections:
    - fortinet.fortiflexvm
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Get entitlement list
      fortinet.fortiflexvm.fortiflexvm_entitlements_list_info:
        username: "{{ username }}"
        password: "{{ password }}"
        # Either configId or (accountId and programSerialNumber) should be provided.
        configId: 22
        # accountId: 12345
        # programSerialNumber: "ELAVMS00XXXXX"
      register: result

    - name: Display response
      debug:
        var: result.entitlements