- name: Create hardware entitlements
  hosts: localhost
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Create hardware entitlements
      fortinet.fortiflexvm.fortiflexvm_entitlements_hardware_create:
        username: "{{ username }}"
        password: "{{ password }}"
        configId: 42
        serialNumbers:
          - "FGT60FTK00000000"
          - "FGT60FTK00000001"
        # endDate: "2023-11-11T00:00:00" # Optional. If not set, it will use the program end date automatically.
      register: result

    - name: Display response
      ansible.builtin.debug:
        var: result.entitlements
