- name: Get information of target entitlements.
  hosts: localhost
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Get entitlement list
      fortinet.fortiflexvm.fortiflexvm_entitlements_list_info:
        username: "{{ username }}"
        password: "{{ password }}"
        # Either configId or (accountId and programSerialNumber) should be provided.
        configId: 22
        # accountId: 12345
        # programSerialNumber: "ELAVMS00XXXXX"

        # Optional filter options
        # description: "you can use description to distinguish entitlements"
        # serialNumber: "XXXXXX0000000000"
        # status: "PENDING"
        # tokenStatus: "NOTUSED"
      register: result

    - name: Display response
      ansible.builtin.debug:
        var: result.entitlements
