- name: Create cloud entitlement.
  hosts: localhost
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Create Cloud Entitlement.
      fortinet.fortiflexvm.fortiflexvm_entitlements_cloud_create:
        username: "{{ username }}"
        password: "{{ password }}"
        configId: 12345
        endDate: "2024-02-12T00:00:00" # Optional. If not set, it will use the program end date automatically.
      register: result

    - name: Display response
      ansible.builtin.debug:
        var: result.entitlements
