- name: Create hardware entitlements
  hosts: localhost
  collections:
    - fortinet.fortiflexvm
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Create hardware entitlements
      fortinet.fortiflexvm.fortiflexvm_entitlements_hardware_create:
        username: "{{ username }}"
        password: "{{ password }}"
        configId: 42
        serialNumbers:
          - "FGT60FTK19000010"
          - "FGT60FTK19000013"
        endDate: "2023-11-11T00:00:00"
      register: result

    - name: Display response
      debug:
        var: result.entitlements
