- name: Get point usage for entitlements
  hosts: localhost
  collections:
    - fortinet.fortiflexvm
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Get entitlements points
      fortinet.fortiflexvm.fortiflexvm_entitlements_points_info:
        username: "{{ username }}"
        password: "{{ password }}"
        # Either configId or (accountId and programSerialNumber) should be provided.
        # configId: 3196
        accountId: 12345
        programSerialNumber: "ELAVMS0XXXXXX"
        # Instead of configId you can pass serialNumber to get results for one VM only.
        serialNumber: "FZVMMLTMXXXXXX"
        startDate: "2020-10-01"
        endDate: "2020-10-25"
      register: result

    - name: Display response
      debug:
        var: result.entitlements