- name: Get next available (unused) token
  hosts: localhost
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Get groups nexttoken
      fortinet.fortiflexvm.fortiflexvm_groups_nexttoken_info:
        username: "{{ username }}"
        password: "{{ password }}"
        # Please declare at least one of the following two arguments: accountId or configId.
        # You can comment at most one argument that you don't want to specify.
        configId: 22
        # accountId: 12345

        # Optional parameters
        folderPath: "My Assets"
        status: ["ACTIVE", "PENDING"] # "ACTIVE", "PENDING", "STOPPED", "EXPIRED"
      register: result

    - name: Display response
      ansible.builtin.debug:
        var: result.entitlements
