- name: Get next available (unused) token
  hosts: localhost
  collections:
    - fortinet.fortiflexvm
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Get groups nexttoken
      fortinet.fortiflexvm.fortiflexvm_groups_nexttoken_info:
        username: "{{ username }}"
        password: "{{ password }}"
        # Please declare at least one of the following two arguments: folderPath and configId.
        # You can comment at most one argument that you don't want to specify.
        folderPath: "My Assets"
        configId: 22
        # accountId: 12345 # optional
      register: result

    - name: Display response
      debug:
        var: result.entitlements