- name: Get list of FortiFlex Programs for the account
  hosts: localhost
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Get programs list
      fortinet.fortiflexvm.fortiflexvm_programs_list_info:
        username: "{{ username }}"
        password: "{{ password }}"
      register: result

    - name: Display response
      ansible.builtin.debug:
        var: result.programs
