- name: Estimate cost
  hosts: localhost
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Estimate cost
      fortinet.fortiflexvm.fortiflexvm_tools_calc_info:
        username: "{{ username }}"
        password: "{{ password }}"
        programSerialNumber: "ELAVMS0000000000"
        # "count" should be 1 if product is cloud (fortiCloudPublic, fortiClientEMSCloud, fortiSASE, fortiEDR).
        count: 1

        # Please only use one of the following.
        fortiGateBundle:
          cpu: 2                              # 1 ~ 96
          service: "UTP"                      # "FC", "UTP", "ENT", "ATP"
          vdom: 10                            # 0 ~ 500
          fortiGuardServices: ["FGTFAIS"]     # ["FGTAVDB", "FGTFAIS", "FGTISSS", "FGTDLDB", "FGTFGSA", "FGTFCSS"]
          cloudServices: ["FGTFAMS"]          # ["FGTFAMS", "FGTSWNM", "FGTSOCA", "FGTFAZC", "FGTSWOS", "FGTFSPA"]
          supportService: "NONE"              # "FGTFCELU", "NONE"

        # fortiManager:
        #   device: 1                         # 1 ~ 100000
        #   adom: 1                           # 1 ~ 100000

        # fortiWeb:
        #   cpu: "4"                          # "1", "2", "4", "8", "16"
        #   service: "FWBSTD"                 # "FWBSTD" or "FWBADV"

        # fortiGateLCS:
        #   cpu: 4                            # 1 ~ 96
        #   fortiGuardServices: []            # "IPS", "AVDB", "FGSA", "DLDB", "FAIS", "FURLDNS"
        #   supportService: "FC247"           # "FC247", "ASET"
        #   vdom: 1                           # 1 ~ 500
        #   cloudServices: ["FAMS", "SWNM"]   # "FAMS", "SWNM", "AFAC", "FAZC"

        # fortiClientEMSOP:
        #   ZTNA: 1000                        # Value should be 0 or between 25 and 25000.
        #   EPP: 1000                         # Value should be 0 or between 25 and 25000.
        #   chromebook: 1000                  # Value should be 0 or between 25 and 25000.
        #   service: "FCTFC247"               # "FCTFC247"
        #   addons: ["BPS"]                   # Empty or "BPS"

        # fortiAnalyzer:
        #   storage: 5                        # 5 ~ 8300
        #   adom: 1                           # 0 ~ 1200
        #   service: "FAZFC247"               # "FAZFC247"

        # fortiPortal:
        #   device: 1                         # 0 ~ 100000

        # fortiADC:
        #   cpu: "32"                         # "1", "2", "4", "8", "16", "32"
        #   service: "FDVSTD"                 # "FDVSTD", "FDVADV" or "FDVFC247"

        # fortiGateHardware:
        #   model: "FGT60F"                   # For all supported modules, please check FNDN.
        #                                     # "FGT40F", "FGT60F", "FGT70F", "FGT80F", "FG100F", "FGT60E", "FGT61F",
        #                                     # "FG100E", "FG101F", "FG200E", "FG200F", "FG201F", "FG4H0F", "FG6H0F",
        #                                     # "FWF40F", "FWF60F", "FGR60F", "FR70FB", "FGT81F", "FG101E", "FG4H1F",
        #                                     # "FG1K0F", "FG180F", "F2K60F", "FG3K0F", "FG3K1F", "FG3K2F"...
        #   service: "FGHWFCEL"               # "FGHWFC247", "FGHWFCEL", "FDVFC247", "FGHWUTP" or "FGHWENT"
        #   addons: []                        # "FGHWFCELU", "FGHWFAMS", "FGHWFAIS", "FGHWSWNM", "FGHWDLDB",
        #                                     # "FGHWFAZC", "FGHWSOCA", "FGHWMGAS", "FGHWSPAL", "FGHWFCSS"

        # fortiCloudPublic:
        #   throughput: 100                   # 25, 50, 75, 100, 150, 200, 250, 300, 350, 400, 450, 500, 600, 700, 800,
        #                                     # 900, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000, 5500, 6000, 6500,
        #                                     # 7000, 7500, 8000, 8500, 9000, 9500, 10000.
        #   applications: 10                  # 0 ~ 2000

        # fortiClientEMSCloud:
        #   ZTNA: 100                         # Value should be 0 or between 25 and 25000.
        #   ZTNA_FGF: 100                     # Value should be 0 or between 25 and 25000.
        #   EPP_ZTNA: 100                     # Value should be 0 or between 25 and 25000.
        #   EPP_ZTNA_FGF: 100                 # Value should be 0 or between 25 and 25000.
        #   chromebook: 100                   # Value should be 0 or between 25 and 25000.
        #   addons: ["BPS"]                   # [] or "BPS"

        # fortiSASE:
        #   users: 50                         # 50 ~ 50000. Value should be divisible by 25.
        #   service: "FSASESTD"               # "FSASESTD" (Standard) or "FSASEADV" (Advanced).
        #   bandwidth: 100                    # 25 ~ 10000. Value should be divisible by 25.
        #   dedicatedIPs: 10                  # 4 ~ 65534

        # fortiEDR:
        #   service: "FEDRPDR"                # "FEDRPDR" (Discover/Protect/Respond)
        #   endpoints: 10                     # Value should be between 0 and 50000
        #   addons: ["FEDRXDR"]               # Empty list or "FEDRXDR"
      register: result

    - name: Display response
      ansible.builtin.debug:
        var: result
