- name: Update VM
  hosts: localhost
  collections:
    - fortinet.fortiflexvm
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Update a Virtual Machine
      fortinet.fortiflexvm.fortiflexvm_vms_update:
        username: "{{ username }}"
        password: "{{ password }}"
        serialNumber: "FGVMMLTM23001324"
        # Please specify configId if you want to update configId, description or endDate
        configId: 3196
        description: "Modify through Ansible"
        endDate: "2023-12-12T00:00:00"
        status: "ACTIVE" # ACTIVE or STOPPED
        regenerateToken: False
      register: result

    - name: Display response
      debug:
        var: result.vms