- name: Get list of VMs for a specific config ID
  hosts: localhost
  collections:
    - fortinet.fortiflexvm
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Get VMs list
      fortinet.fortiflexvm.fortiflexvm_vms_list_info:
        username: "{{ username }}"
        password: "{{ password }}"
        configId: 22
      register: result

    - name: Display response
      debug:
        var: result.vms